[package]
name = "catfetch"
version = "1.1.0" # error handling is a feature now
edition = "2024"

[features]
default = [ "error_handling" ]
error_handling = [ "dep:anyhow" ]

[dependencies.anyhow]
version = "1.0.95"
default-features = false
optional = true
