[package]
name = "catfetch"
version = "1.2.0" # makefile, fallbacks, tweaks
edition = "2024"
authors = [ "Toxikuu" ]
description = "cute fetch script featuring a cat"
license = "GPL-3.0"

[profile.release]
strip = "symbols"
lto = "fat"
panic = "abort"

[features]
default = [ "error_handling" ]
error_handling = [ "dep:anyhow" ]

[dependencies.anyhow]
version = "1"
default-features = false
optional = true
